"""Regenerate remotion/src/fonts.css by inlining the Inter TTFs as base64 data
URIs. Run when fonts/Inter-*.ttf change:  python -m scripts.build_fonts_css

The fonts are embedded so the Remotion render never does a network fetch for
them — a stalled fetch on a busy CI runner used to hang delayRender and fail
the whole render.
"""
import base64
import os

ROOT = os.path.dirname(os.path.dirname(__file__))
FACES = [("Inter-Bold.ttf", 700), ("Inter-Regular.ttf", 400)]


def _uri(path):
    return "data:font/ttf;base64," + base64.b64encode(open(path, "rb").read()).decode()


def build():
    rules = [
        "/* AUTO-GENERATED by scripts/build_fonts_css.py — base64 of fonts/Inter-*.ttf.\n"
        "   Inlined so the Remotion render never network-fetches the font. */"
    ]
    for fname, weight in FACES:
        uri = _uri(os.path.join(ROOT, "fonts", fname))
        rules.append(
            "@font-face {\n"
            "  font-family: 'Inter';\n"
            f"  font-weight: {weight};\n"
            "  font-style: normal;\n"
            f"  src: url('{uri}') format('truetype');\n"
            "}"
        )
    out = os.path.join(ROOT, "remotion", "src", "fonts.css")
    with open(out, "w") as f:
        f.write("\n".join(rules) + "\n")
    print(f"wrote {out} ({os.path.getsize(out)} bytes)")


if __name__ == "__main__":
    build()
